name: foodapp
description: FoodApp - Ứng dụng bán đồ ăn nhanh nhanh

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_dotenv: ^5.0.2
  file_picker: ^6.1.1
  permission_handler: 11.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  http_parser:

  cupertino_icons: ^1.0.2
  firebase_auth:
  firebase_messaging: ^14.7.8
  firebase_core: ^2.24.2
  firebase_storage:
  cloud_firestore: ^4.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/iconLogo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/bottomBar/
    - .env


